import { defineCardDesign, type CardDesignRecord } from './cardDesign.js';

export const ALLIED_CARD_DESIGNS: readonly CardDesignRecord[] = Object.freeze([
  defineCardDesign({
    faction: 'ALLIED',
    definition: {
      id: 'allied-leader-aelira',
      name: '태양잎 여왕 아엘리라',
      description: '태양숲 원정대를 이끌며 꾸준한 보급으로 전선을 넓히는 엘프 여왕이다.',
      type: 'LEADER',
      cost: 0,
      dominance: 2,
      hp: 20,
      attack: 0,
      activeSkill: {
        id: 'allied-leader-aelira-sunlit-command',
        description: 'DRAW를 선택하면 기본 드로우 뒤 카드 1장을 추가로 뽑는다.',
        type: 'ACTIVE',
        action: 'DRAW',
        effects: [{ type: 'DRAW', target: 'OWNER', count: 1 }],
      },
    },
    rarity: 'LEGENDARY',
    primaryRole: 'HAND',
    secondaryRole: 'OCCUPATION',
    deckQuantity: 1,
    expectedSkillValue: 2,
    artDirection: {
      scene: 'sunlit throne grown into the roots of an immense world tree',
      equipment: 'leaf-shaped scepter and layered ceremonial mantle',
      palette: 'warm gold, emerald green, and ivory',
      pose: 'standing front-facing with the scepter raised in calm command',
    },
  }),
  defineCardDesign({
    faction: 'ALLIED',
    definition: {
      id: 'allied-sunroot-pathfinder',
      name: '태양뿌리 길잡이',
      description: '세계수의 뿌리길을 밝혀 아군이 설 자리를 넓히는 정찰병이다.',
      type: 'UNIT',
      cost: 1,
      dominance: 1,
      hp: 2,
      attack: 0,
      passiveSkill: {
        id: 'allied-sunroot-pathfinder-deep-routes',
        description: 'Field에 있는 동안 이 카드의 지배력을 1 높인다.',
        type: 'PASSIVE',
        effects: [{ type: 'MODIFY_STAT', target: 'SELF', stat: 'DOMINANCE', amount: 1 }],
      },
    },
    rarity: 'COMMON',
    primaryRole: 'OCCUPATION',
    secondaryRole: null,
    deckQuantity: 2,
    expectedSkillValue: 1.5,
    artDirection: {
      scene: 'a luminous trail winding between giant moss-covered roots',
      equipment: 'leaf-vein compass and short ash spear',
      palette: 'fresh green, honey gold, and bark brown',
      pose: 'kneeling forward while pointing the compass toward an open path',
    },
  }),
  defineCardDesign({
    faction: 'ALLIED',
    definition: {
      id: 'allied-dawn-scribe',
      name: '새벽 기록관',
      description: '전황을 빛의 두루마리에 새겨 원정대의 다음 수를 준비하는 기록관이다.',
      type: 'UNIT',
      cost: 1,
      dominance: 1,
      hp: 1,
      attack: 0,
      activeSkill: {
        id: 'allied-dawn-scribe-living-chronicle',
        description: 'DRAW를 선택하면 기본 드로우 뒤 카드 1장을 추가로 뽑는다.',
        type: 'ACTIVE',
        action: 'DRAW',
        effects: [{ type: 'DRAW', target: 'OWNER', count: 1 }],
      },
    },
    rarity: 'COMMON',
    primaryRole: 'HAND',
    secondaryRole: null,
    deckQuantity: 2,
    expectedSkillValue: 2,
    artDirection: {
      scene: 'an open-air elven archive at sunrise',
      equipment: 'glowing scroll case and crystal stylus',
      palette: 'pale gold, sky blue, and parchment cream',
      pose: 'turning sideways as a ribbon of written light circles one hand',
    },
  }),
  defineCardDesign({
    faction: 'ALLIED',
    definition: {
      id: 'allied-mossguard',
      name: '이끼방패 수호자',
      description: '살아 있는 이끼방패로 충격을 흡수하며 전선을 지키는 수호자다.',
      type: 'UNIT',
      cost: 1,
      dominance: 1,
      hp: 2,
      attack: 0,
      reactiveSkill: {
        id: 'allied-mossguard-renewing-moss',
        description: '이 카드가 피해를 받으면 이 카드의 피해를 1 회복한다.',
        type: 'REACTIVE',
        trigger: { type: 'DAMAGE_RECEIVED', subject: 'SELF' },
        effects: [{ type: 'HEAL', target: 'SELF', amount: 1 }],
      },
    },
    rarity: 'COMMON',
    primaryRole: 'DEFENSE',
    secondaryRole: null,
    deckQuantity: 2,
    expectedSkillValue: 1.5,
    artDirection: {
      scene: 'a rain-damp forest gate woven from living branches',
      equipment: 'broad moss-covered wooden shield and short sword',
      palette: 'moss green, muted bronze, and rain gray',
      pose: 'braced behind the shield with one shoulder lowered',
    },
  }),
  defineCardDesign({
    faction: 'ALLIED',
    definition: {
      id: 'allied-amber-duelist',
      name: '호박빛 결투가',
      description: '가벼운 칼날과 빠른 발놀림으로 초반 전선을 압박하는 결투가다.',
      type: 'UNIT',
      cost: 1,
      dominance: 1,
      hp: 1,
      attack: 2,
    },
    rarity: 'COMMON',
    primaryRole: 'ATTACK',
    secondaryRole: null,
    deckQuantity: 2,
    expectedSkillValue: 0,
    artDirection: {
      scene: 'a circular amber-leaf dueling terrace',
      equipment: 'slender leaf saber and light leather vambrace',
      palette: 'amber, russet red, and forest green',
      pose: 'lunging in a compact fencing stance with the blade extended',
    },
  }),
  defineCardDesign({
    faction: 'ALLIED',
    definition: {
      id: 'allied-pollen-saboteur',
      name: '꽃가루 교란자',
      description: '눈부신 꽃가루를 흩뿌려 상대의 손패 계획을 흐트러뜨리는 교란자다.',
      type: 'UNIT',
      cost: 2,
      dominance: 1,
      hp: 3,
      attack: 1,
      activeSkill: {
        id: 'allied-pollen-saboteur-blinding-cloud',
        description: 'DISCARD를 선택하면 상대가 손패 1장을 버린다.',
        type: 'ACTIVE',
        action: 'DISCARD',
        effects: [{ type: 'DISCARD', target: 'OPPONENT', count: 1 }],
      },
    },
    rarity: 'COMMON',
    primaryRole: 'DISRUPTION',
    secondaryRole: 'HAND',
    deckQuantity: 2,
    expectedSkillValue: 2,
    artDirection: {
      scene: 'a flower-choked woodland choke point filled with drifting pollen',
      equipment: 'seed-pod grenades and hooked utility knife',
      palette: 'sunflower yellow, sage green, and soft violet',
      pose: 'twisting away while casting a bright cloud from an open palm',
    },
  }),
  defineCardDesign({
    faction: 'ALLIED',
    definition: {
      id: 'allied-vine-cartographer',
      name: '덩굴 지도사',
      description: '움직이는 덩굴 지도를 펼쳐 아군의 지배망을 안정시키는 지도사다.',
      type: 'UNIT',
      cost: 2,
      dominance: 1,
      hp: 4,
      attack: 1,
      passiveSkill: {
        id: 'allied-vine-cartographer-living-map',
        description: 'Field에 있는 동안 이 카드의 지배력을 1 높인다.',
        type: 'PASSIVE',
        effects: [{ type: 'MODIFY_STAT', target: 'SELF', stat: 'DOMINANCE', amount: 1 }],
      },
    },
    rarity: 'COMMON',
    primaryRole: 'OCCUPATION',
    secondaryRole: null,
    deckQuantity: 2,
    expectedSkillValue: 1.5,
    artDirection: {
      scene: 'a high wooden survey platform above the forest canopy',
      equipment: 'living vine map and brass measuring staff',
      palette: 'deep green, antique brass, and cloud white',
      pose: 'holding the unfurled map wide while marking a route with the staff',
    },
  }),
  defineCardDesign({
    faction: 'ALLIED',
    definition: {
      id: 'allied-seed-oracle',
      name: '씨앗 예언가',
      description: '버려진 가능성에서 새 전조를 읽어 손패의 흐름을 되살리는 예언가다.',
      type: 'UNIT',
      cost: 2,
      dominance: 1,
      hp: 4,
      attack: 0,
      reactiveSkill: {
        id: 'allied-seed-oracle-second-omen',
        description: '아군 카드가 버려지면 카드 1장을 뽑는다.',
        type: 'REACTIVE',
        trigger: { type: 'CARD_DISCARDED', subject: 'OWNER' },
        effects: [{ type: 'DRAW', target: 'OWNER', count: 1 }],
      },
    },
    rarity: 'RARE',
    primaryRole: 'HAND',
    secondaryRole: null,
    deckQuantity: 2,
    expectedSkillValue: 2.5,
    artDirection: {
      scene: 'a moonwell garden scattered with floating prophetic seeds',
      equipment: 'carved seed reliquary and crescent sickle',
      palette: 'mint green, pearl white, and soft teal',
      pose: 'cupping a germinating seed while looking into its reflected vision',
    },
  }),
  defineCardDesign({
    faction: 'ALLIED',
    definition: {
      id: 'allied-gleam-lancer',
      name: '햇살 창기병',
      description: '응축한 햇살을 창끝에 실어 방어선을 돌파하는 선봉 기병이다.',
      type: 'UNIT',
      cost: 3,
      dominance: 1,
      hp: 5,
      attack: 3,
      activeSkill: {
        id: 'allied-gleam-lancer-piercing-ray',
        description: 'ATTACK을 선택하면 공격 대상에게 피해 1을 추가로 준다.',
        type: 'ACTIVE',
        action: 'ATTACK',
        effects: [{ type: 'DAMAGE', target: 'ACTION_TARGET', amount: 1 }],
      },
    },
    rarity: 'COMMON',
    primaryRole: 'ATTACK',
    secondaryRole: null,
    deckQuantity: 2,
    expectedSkillValue: 1,
    artDirection: {
      scene: 'a sunbeam cutting through a fern-covered battlefield',
      equipment: 'long crystal-tipped lance and fitted scale armor',
      palette: 'bright gold, fern green, and polished silver',
      pose: 'driving forward with the lance leveled in both hands',
    },
  }),
  defineCardDesign({
    faction: 'ALLIED',
    definition: {
      id: 'allied-bark-shield',
      name: '껍질방패 파수꾼',
      description: '두꺼운 수피 갑옷으로 상처를 봉합하며 오래 버티는 파수꾼이다.',
      type: 'UNIT',
      cost: 3,
      dominance: 2,
      hp: 5,
      attack: 1,
      reactiveSkill: {
        id: 'allied-bark-shield-seal-the-wound',
        description: '이 카드가 피해를 받으면 이 카드의 피해를 1 회복한다.',
        type: 'REACTIVE',
        trigger: { type: 'DAMAGE_RECEIVED', subject: 'SELF' },
        effects: [{ type: 'HEAL', target: 'SELF', amount: 1 }],
      },
    },
    rarity: 'RARE',
    primaryRole: 'DEFENSE',
    secondaryRole: null,
    deckQuantity: 2,
    expectedSkillValue: 1.5,
    artDirection: {
      scene: 'a fortified grove entrance beneath interlocked branches',
      equipment: 'tower shield of layered bark and heavy leaf-edged mace',
      palette: 'cedar brown, dark green, and copper',
      pose: 'standing squarely with the tower shield planted into the ground',
    },
  }),
  defineCardDesign({
    faction: 'ALLIED',
    definition: {
      id: 'allied-grove-renewer',
      name: '숲의 되살림사',
      description: '쓰러진 아군을 뿌리에서 다시 일으키는 고대 숲의 치유사다.',
      type: 'UNIT',
      cost: 3,
      dominance: 2,
      hp: 3,
      attack: 0,
      reactiveSkill: {
        id: 'allied-grove-renewer-return-to-light',
        description: '단일 아군 유닛이 파괴되면 그 유닛을 Drop에서 Field에 배치한다.',
        type: 'REACTIVE',
        trigger: { type: 'CARD_DESTROYED', subject: 'OWNER' },
        effects: [{ type: 'PLACE', target: 'TRIGGER_SUBJECT' }],
      },
      passiveSkill: {
        id: 'allied-grove-renewer-ancient-vitality',
        description: 'Field에 있는 동안 이 카드의 체력을 1 높인다.',
        type: 'PASSIVE',
        effects: [{ type: 'MODIFY_STAT', target: 'SELF', stat: 'HEALTH', amount: 1 }],
      },
    },
    rarity: 'EPIC',
    primaryRole: 'RECOVERY',
    secondaryRole: 'DEFENSE',
    deckQuantity: 2,
    expectedSkillValue: 3.5,
    artDirection: {
      scene: 'a quiet grove where fallen leaves rise into green light',
      equipment: 'rootwood healing staff and satchel of luminous herbs',
      palette: 'jade green, soft white, and rose gold',
      pose: 'kneeling with the staff grounded as spiraling leaves lift around her',
    },
  }),
  defineCardDesign({
    faction: 'ALLIED',
    definition: {
      id: 'allied-solar-blade',
      name: '태양검 선봉장',
      description: '태양의 열기를 검에 모아 정면의 적을 베어 넘기는 선봉장이다.',
      type: 'UNIT',
      cost: 4,
      dominance: 2,
      hp: 4,
      attack: 3,
      activeSkill: {
        id: 'allied-solar-blade-corona-cut',
        description: 'ATTACK을 선택하면 공격 대상에게 피해 2를 추가로 준다.',
        type: 'ACTIVE',
        action: 'ATTACK',
        effects: [{ type: 'DAMAGE', target: 'ACTION_TARGET', amount: 2 }],
      },
    },
    rarity: 'RARE',
    primaryRole: 'ATTACK',
    secondaryRole: null,
    deckQuantity: 2,
    expectedSkillValue: 2,
    artDirection: {
      scene: 'a golden clearing split by a descending shaft of sunlight',
      equipment: 'broad sunsteel sword and articulated leaf plate',
      palette: 'white gold, orange, and deep green',
      pose: 'swinging the radiant sword in a powerful diagonal arc',
    },
  }),
  defineCardDesign({
    faction: 'ALLIED',
    definition: {
      id: 'allied-canopy-warden',
      name: '수관 감시자',
      description: '높은 수관에서 적의 돌진을 읽고 공격의 힘을 꺾는 감시자다.',
      type: 'UNIT',
      cost: 4,
      dominance: 3,
      hp: 6,
      attack: 1,
      reactiveSkill: {
        id: 'allied-canopy-warden-breaking-warning',
        description: '상대가 공격을 선언하면 그 공격자의 공격력을 1 낮춘다.',
        type: 'REACTIVE',
        trigger: { type: 'ATTACK_DECLARED', subject: 'OPPONENT' },
        effects: [
          {
            type: 'MODIFY_STAT',
            target: 'TRIGGER_SOURCE',
            stat: 'ATTACK',
            amount: -1,
          },
        ],
      },
    },
    rarity: 'COMMON',
    primaryRole: 'DEFENSE',
    secondaryRole: 'DISRUPTION',
    deckQuantity: 2,
    expectedSkillValue: 1.5,
    artDirection: {
      scene: 'a rope bridge high above a dense green canopy',
      equipment: 'long recurve bow and layered bark pauldrons',
      palette: 'pine green, tan leather, and muted gold',
      pose: 'drawing the bow downward from a steady elevated stance',
    },
  }),
  defineCardDesign({
    faction: 'ALLIED',
    definition: {
      id: 'allied-worldtree-anchor',
      name: '세계수 닻지기',
      description: '거대한 뿌리닻으로 전선을 고정하고 넓은 지배망을 만드는 중장병이다.',
      type: 'UNIT',
      cost: 5,
      dominance: 3,
      hp: 8,
      attack: 2,
      passiveSkill: {
        id: 'allied-worldtree-anchor-rooted-domain',
        description: 'Field에 있는 동안 이 카드의 지배력을 1 높인다.',
        type: 'PASSIVE',
        effects: [{ type: 'MODIFY_STAT', target: 'SELF', stat: 'DOMINANCE', amount: 1 }],
      },
    },
    rarity: 'EPIC',
    primaryRole: 'OCCUPATION',
    secondaryRole: 'DEFENSE',
    deckQuantity: 2,
    expectedSkillValue: 1.5,
    artDirection: {
      scene: 'the base of a colossal world tree during a defensive stand',
      equipment: 'massive root-shaped anchor hammer and heavy wooden plate',
      palette: 'ancient brown, emerald, and bronze',
      pose: 'planting the anchor hammer into the earth with both hands',
    },
  }),
  defineCardDesign({
    faction: 'ALLIED',
    definition: {
      id: 'allied-twilight-exiler',
      name: '황혼 추방자',
      description: '황혼의 경계를 베어 강한 적을 전장에서 완전히 몰아내는 사냥꾼이다.',
      type: 'UNIT',
      cost: 6,
      dominance: 2,
      hp: 7,
      attack: 2,
      activeSkill: {
        id: 'allied-twilight-exiler-sever-from-dawn',
        description: 'ATTACK을 선택하면 공격 대상에게 EXILED 상태를 추가한다.',
        type: 'ACTIVE',
        action: 'ATTACK',
        effects: [{ type: 'ADD_STATUS', target: 'ACTION_TARGET', statusId: 'EXILED' }],
      },
      reactiveSkill: {
        id: 'allied-twilight-exiler-last-light',
        description: '이 카드가 피해를 받으면 그 피해를 준 카드에게 피해 1을 준다.',
        type: 'REACTIVE',
        trigger: { type: 'DAMAGE_RECEIVED', subject: 'SELF' },
        effects: [{ type: 'DAMAGE', target: 'TRIGGER_SOURCE', amount: 1 }],
      },
    },
    rarity: 'EPIC',
    primaryRole: 'DISRUPTION',
    secondaryRole: 'ATTACK',
    deckQuantity: 2,
    expectedSkillValue: 5.5,
    artDirection: {
      scene: 'a forest threshold divided between sunset and starlight',
      equipment: 'crescent greatblade and warded hunter cloak',
      palette: 'violet, burnt orange, and dark teal',
      pose: 'holding the greatblade across her body as a rift opens behind the edge',
    },
  }),
  defineCardDesign({
    faction: 'ALLIED',
    definition: {
      id: 'allied-golden-champion',
      name: '황금숲 대전사',
      description: '긴 전쟁에서 단련된 힘으로 적의 전열을 무너뜨리는 원정대의 대전사다.',
      type: 'UNIT',
      cost: 7,
      dominance: 3,
      hp: 9,
      attack: 7,
    },
    rarity: 'RARE',
    primaryRole: 'ATTACK',
    secondaryRole: 'DEFENSE',
    deckQuantity: 1,
    expectedSkillValue: 0,
    artDirection: {
      scene: 'a broad golden forest battlefield after a storm',
      equipment: 'two-handed glaive and reinforced ceremonial plate',
      palette: 'rich gold, dark oak, and crimson accents',
      pose: 'standing in a wide grounded stance with the glaive held diagonally',
    },
  }),
]);
