import { defineCardDesign, type CardDesignRecord } from './cardDesign.js';

export const ENEMY_CARD_DESIGNS: readonly CardDesignRecord[] = Object.freeze([
  defineCardDesign({
    faction: 'ENEMY',
    definition: {
      id: 'enemy-leader-velsara',
      name: '월식 여왕 벨사라',
      description: '검은가시 군단을 지휘하며 자신을 해친 적에게 월식의 상처를 돌려주는 여왕이다.',
      type: 'LEADER',
      cost: 0,
      dominance: 2,
      hp: 20,
      attack: 0,
      reactiveSkill: {
        id: 'enemy-leader-velsara-eclipse-reprisal',
        description: '이 카드가 피해를 받으면 그 피해를 준 카드에게 피해 1을 준다.',
        type: 'REACTIVE',
        trigger: { type: 'DAMAGE_RECEIVED', subject: 'SELF' },
        effects: [{ type: 'DAMAGE', target: 'TRIGGER_SOURCE', amount: 1 }],
      },
    },
    rarity: 'LEGENDARY',
    primaryRole: 'DISRUPTION',
    secondaryRole: 'DEFENSE',
    deckQuantity: 1,
    expectedSkillValue: 2,
    artDirection: {
      scene: 'an obsidian throne beneath a total lunar eclipse',
      equipment: 'blackthorn crown staff and layered royal battle mantle',
      palette: 'black violet, cold silver, and deep crimson',
      pose: 'standing in composed profile while pointing the crown staff at an unseen foe',
    },
  }),
  defineCardDesign({
    faction: 'ENEMY',
    definition: {
      id: 'enemy-nightroot-scout',
      name: '밤뿌리 척후병',
      description: '어둠 속 뿌리길을 점거해 군단의 침투로를 넓히는 척후병이다.',
      type: 'UNIT',
      cost: 1,
      dominance: 1,
      hp: 2,
      attack: 0,
      passiveSkill: {
        id: 'enemy-nightroot-scout-hidden-routes',
        description: 'Field에 있는 동안 이 카드의 지배력을 1 높인다.',
        type: 'PASSIVE',
        effects: [{ type: 'MODIFY_STAT', target: 'SELF', stat: 'DOMINANCE', amount: 1 }],
      },
    },
    rarity: 'COMMON',
    primaryRole: 'OCCUPATION',
    secondaryRole: null,
    deckQuantity: 2,
    expectedSkillValue: 1.5,
    artDirection: {
      scene: 'a subterranean root tunnel lit by violet fungi',
      equipment: 'hooked scout spear and dark glass compass',
      palette: 'indigo, charcoal, and fungal violet',
      pose: 'crouching low while tracing a hidden route with the spear tip',
    },
  }),
  defineCardDesign({
    faction: 'ENEMY',
    definition: {
      id: 'enemy-gloam-whisperer',
      name: '땅거미 속삭임꾼',
      description: '땅거미의 속삭임으로 상대의 손패를 흔드는 음모가다.',
      type: 'UNIT',
      cost: 1,
      dominance: 1,
      hp: 1,
      attack: 0,
      activeSkill: {
        id: 'enemy-gloam-whisperer-unravel-thought',
        description: 'Active 사용 시 상대가 손패 1장을 버린다.',
        type: 'ACTIVE',
        action: 'DRAW',
        effects: [{ type: 'DISCARD', target: 'OPPONENT', count: 1 }],
      },
    },
    rarity: 'COMMON',
    primaryRole: 'HAND',
    secondaryRole: 'DISRUPTION',
    deckQuantity: 2,
    expectedSkillValue: 2,
    artDirection: {
      scene: 'a twilight colonnade filled with drifting black petals',
      equipment: 'whispering fan of raven feathers and slim ritual dagger',
      palette: 'dusky purple, black, and faded rose',
      pose: 'leaning slightly forward as dark whispers coil from the open fan',
    },
  }),
  defineCardDesign({
    faction: 'ENEMY',
    definition: {
      id: 'enemy-obsidian-guard',
      name: '흑요석 근위대',
      description: '공격의 기세를 흑요석 방패에 흘려 보내는 냉정한 근위병이다.',
      type: 'UNIT',
      cost: 1,
      dominance: 1,
      hp: 2,
      attack: 0,
      reactiveSkill: {
        id: 'enemy-obsidian-guard-dulling-ward',
        description: '상대가 공격을 선언하면 그 공격자의 공격력을 1 낮춘다.',
        type: 'REACTIVE',
        trigger: { type: 'ATTACK_DECLARED', subject: 'OPPONENT' },
        effects: [
          {
            type: 'MODIFY_STAT',
            target: 'TRIGGER_SOURCE',
            stat: 'ATTACK',
            amount: -1,
          },
        ],
      },
    },
    rarity: 'COMMON',
    primaryRole: 'DEFENSE',
    secondaryRole: 'DISRUPTION',
    deckQuantity: 2,
    expectedSkillValue: 1.5,
    artDirection: {
      scene: 'a narrow gate of polished black stone',
      equipment: 'faceted obsidian shield and short crescent blade',
      palette: 'glossy black, steel gray, and violet highlights',
      pose: 'holding the shield high while angling the blade behind it',
    },
  }),
  defineCardDesign({
    faction: 'ENEMY',
    definition: {
      id: 'enemy-crimson-duelist',
      name: '진홍 결투가',
      description: '짧고 치명적인 검로로 빈틈을 파고드는 군단의 결투가다.',
      type: 'UNIT',
      cost: 1,
      dominance: 1,
      hp: 1,
      attack: 2,
    },
    rarity: 'COMMON',
    primaryRole: 'ATTACK',
    secondaryRole: null,
    deckQuantity: 2,
    expectedSkillValue: 0,
    artDirection: {
      scene: 'a rain-slick courtyard under red lanterns',
      equipment: 'paired narrow sabers and fitted dark leather armor',
      palette: 'crimson, black, and wet silver',
      pose: 'cross-stepping into a swift twin-blade strike',
    },
  }),
  defineCardDesign({
    faction: 'ENEMY',
    definition: {
      id: 'enemy-hex-weaver',
      name: '가시주문 직조사',
      description: '적의 무기에 가시주문을 얽어 공격력을 서서히 무너뜨리는 주술사다.',
      type: 'UNIT',
      cost: 2,
      dominance: 1,
      hp: 3,
      attack: 1,
      activeSkill: {
        id: 'enemy-hex-weaver-thorn-bind',
        description: 'Active 사용 시 공격 범위 안의 대상 공격력을 1 낮춘다.',
        type: 'ACTIVE',
        action: 'ATTACK',
        effects: [
          {
            type: 'MODIFY_STAT',
            target: 'ACTION_TARGET',
            stat: 'ATTACK',
            amount: -1,
          },
        ],
      },
    },
    rarity: 'COMMON',
    primaryRole: 'DISRUPTION',
    secondaryRole: 'DEFENSE',
    deckQuantity: 2,
    expectedSkillValue: 2,
    artDirection: {
      scene: 'a ruined shrine overgrown with black thorn vines',
      equipment: 'thorn-thread spindle and curved sacrificial knife',
      palette: 'black green, violet, and tarnished copper',
      pose: 'pulling a taut strand of glowing thorn magic between both hands',
    },
  }),
  defineCardDesign({
    faction: 'ENEMY',
    definition: {
      id: 'enemy-shadow-cartographer',
      name: '그림자 지도사',
      description: '살아 움직이는 그림자 지도로 군단의 지배 영역을 고정하는 지도사다.',
      type: 'UNIT',
      cost: 2,
      dominance: 1,
      hp: 4,
      attack: 1,
      passiveSkill: {
        id: 'enemy-shadow-cartographer-inked-domain',
        description: 'Field에 있는 동안 이 카드의 지배력을 1 높인다.',
        type: 'PASSIVE',
        effects: [{ type: 'MODIFY_STAT', target: 'SELF', stat: 'DOMINANCE', amount: 1 }],
      },
    },
    rarity: 'COMMON',
    primaryRole: 'OCCUPATION',
    secondaryRole: null,
    deckQuantity: 2,
    expectedSkillValue: 1.5,
    artDirection: {
      scene: 'a war table inside a tent of layered black silk',
      equipment: 'shadow-ink map and silver divider compass',
      palette: 'midnight blue, black, and cold silver',
      pose: 'leaning over the floating map while pinning a route with one finger',
    },
  }),
  defineCardDesign({
    faction: 'ENEMY',
    definition: {
      id: 'enemy-raven-oracle',
      name: '까마귀 예언가',
      description: '상대가 얻은 정보를 까마귀의 눈으로 훔쳐 군단의 손패로 바꾸는 예언가다.',
      type: 'UNIT',
      cost: 2,
      dominance: 1,
      hp: 4,
      attack: 0,
      reactiveSkill: {
        id: 'enemy-raven-oracle-stolen-vision',
        description: '상대가 카드를 뽑으면 카드 1장을 뽑는다.',
        type: 'REACTIVE',
        trigger: { type: 'CARD_DRAWN', subject: 'OPPONENT' },
        effects: [{ type: 'DRAW', target: 'OWNER', count: 1 }],
      },
    },
    rarity: 'RARE',
    primaryRole: 'HAND',
    secondaryRole: null,
    deckQuantity: 2,
    expectedSkillValue: 2.5,
    artDirection: {
      scene: 'a dead silver tree crowded with watchful ravens',
      equipment: 'raven-skull focus and crescent-tipped staff',
      palette: 'blue black, pale silver, and amethyst',
      pose: 'extending one gloved arm as a raven lands and shares a vision',
    },
  }),
  defineCardDesign({
    faction: 'ENEMY',
    definition: {
      id: 'enemy-moonfang-raider',
      name: '월아 습격자',
      description: '달빛을 두른 월아창으로 적의 방어선을 찢는 기습병이다.',
      type: 'UNIT',
      cost: 3,
      dominance: 1,
      hp: 5,
      attack: 2,
      activeSkill: {
        id: 'enemy-moonfang-raider-lunar-gouge',
        description: 'Active 사용 시 공격 범위 안의 대상에게 피해 2를 준다.',
        type: 'ACTIVE',
        action: 'ATTACK',
        effects: [{ type: 'DAMAGE', target: 'ACTION_TARGET', amount: 2 }],
      },
    },
    rarity: 'COMMON',
    primaryRole: 'ATTACK',
    secondaryRole: null,
    deckQuantity: 2,
    expectedSkillValue: 2,
    artDirection: {
      scene: 'a moonlit ravine crossed by drifting ground fog',
      equipment: 'crescent-bladed polearm and dark scale coat',
      palette: 'moon silver, navy, and black',
      pose: 'charging uphill with the crescent blade sweeping low',
    },
  }),
  defineCardDesign({
    faction: 'ENEMY',
    definition: {
      id: 'enemy-frostveil-sentinel',
      name: '서리장막 파수꾼',
      description: '새로 등장한 적의 무기에 서리를 씌워 전진 속도를 늦추는 파수꾼이다.',
      type: 'UNIT',
      cost: 3,
      dominance: 2,
      hp: 5,
      attack: 1,
      reactiveSkill: {
        id: 'enemy-frostveil-sentinel-cold-arrival',
        description: '상대 카드가 배치되면 그 카드의 공격력을 1 낮춘다.',
        type: 'REACTIVE',
        trigger: { type: 'CARD_PLACED', subject: 'OPPONENT' },
        effects: [
          {
            type: 'MODIFY_STAT',
            target: 'TRIGGER_SUBJECT',
            stat: 'ATTACK',
            amount: -1,
          },
        ],
      },
    },
    rarity: 'RARE',
    primaryRole: 'DEFENSE',
    secondaryRole: 'DISRUPTION',
    deckQuantity: 2,
    expectedSkillValue: 1.5,
    artDirection: {
      scene: 'a frozen thorn barricade under a dim winter moon',
      equipment: 'ice-rimmed tower shield and straight spear',
      palette: 'frost blue, charcoal, and white silver',
      pose: 'standing behind the shield while directing a stream of frost forward',
    },
  }),
  defineCardDesign({
    faction: 'ENEMY',
    definition: {
      id: 'enemy-gravebloom-revenant',
      name: '무덤꽃 귀환자',
      description: '쓰러질 때마다 무덤꽃의 뿌리를 타고 다시 전장으로 돌아오는 전사다.',
      type: 'UNIT',
      cost: 3,
      dominance: 2,
      hp: 2,
      attack: 0,
      reactiveSkill: {
        id: 'enemy-gravebloom-revenant-return-in-bloom',
        description: '이 카드가 파괴되면 이 카드를 Drop에서 Field에 배치한다.',
        type: 'REACTIVE',
        trigger: { type: 'CARD_DESTROYED', subject: 'SELF' },
        effects: [{ type: 'PLACE', target: 'SELF' }],
      },
      passiveSkill: {
        id: 'enemy-gravebloom-revenant-deathless-vigor',
        description: 'Field에 있는 동안 이 카드의 체력을 1 높인다.',
        type: 'PASSIVE',
        effects: [{ type: 'MODIFY_STAT', target: 'SELF', stat: 'HEALTH', amount: 1 }],
      },
    },
    rarity: 'EPIC',
    primaryRole: 'RECOVERY',
    secondaryRole: 'DEFENSE',
    deckQuantity: 2,
    expectedSkillValue: 4,
    artDirection: {
      scene: 'an ancient elven grave garden bursting with dark flowers',
      equipment: 'gravewood staff and petal-layered ceremonial armor',
      palette: 'burgundy, black green, and bone white',
      pose: 'rising from one knee as luminous roots coil around the staff',
    },
  }),
  defineCardDesign({
    faction: 'ENEMY',
    definition: {
      id: 'enemy-bloodmoon-blade',
      name: '혈월 검무사',
      description: '혈월의 궤적을 따라 연속 참격을 쏟아붓는 검무사다.',
      type: 'UNIT',
      cost: 4,
      dominance: 2,
      hp: 4,
      attack: 3,
      activeSkill: {
        id: 'enemy-bloodmoon-blade-red-arc',
        description: 'Active 사용 시 공격 범위 안의 대상에게 피해 2를 준다.',
        type: 'ACTIVE',
        action: 'ATTACK',
        effects: [{ type: 'DAMAGE', target: 'ACTION_TARGET', amount: 2 }],
      },
    },
    rarity: 'RARE',
    primaryRole: 'ATTACK',
    secondaryRole: null,
    deckQuantity: 2,
    expectedSkillValue: 2,
    artDirection: {
      scene: 'a high blackstone terrace beneath a red moon',
      equipment: 'long curved bloodsteel blade and segmented battle dress',
      palette: 'blood red, black, and pale silver',
      pose: 'turning through a wide horizontal slash that leaves a red arc',
    },
  }),
  defineCardDesign({
    faction: 'ENEMY',
    definition: {
      id: 'enemy-nightwall-warden',
      name: '밤장벽 감시자',
      description: '아군이 입은 상처를 어둠의 장막으로 봉합하는 군단의 감시자다.',
      type: 'UNIT',
      cost: 4,
      dominance: 3,
      hp: 5,
      attack: 1,
      reactiveSkill: {
        id: 'enemy-nightwall-warden-shadow-mend',
        description: '아군 카드가 피해를 받으면 그 카드의 피해를 1 회복한다.',
        type: 'REACTIVE',
        trigger: { type: 'DAMAGE_RECEIVED', subject: 'OWNER' },
        effects: [{ type: 'HEAL', target: 'TRIGGER_SUBJECT', amount: 1 }],
      },
    },
    rarity: 'COMMON',
    primaryRole: 'DEFENSE',
    secondaryRole: null,
    deckQuantity: 2,
    expectedSkillValue: 2,
    artDirection: {
      scene: 'a fortress rampart wrapped in slow-moving shadow',
      equipment: 'black lantern staff and reinforced lamellar cloak',
      palette: 'midnight blue, smoky gray, and violet',
      pose: 'holding the lantern staff overhead as shadow folds around an ally',
    },
  }),
  defineCardDesign({
    faction: 'ENEMY',
    definition: {
      id: 'enemy-blackthorn-anchor',
      name: '검은가시 닻지기',
      description: '검은가시 닻으로 땅을 움켜쥐고 군단의 지배망을 고정하는 중장병이다.',
      type: 'UNIT',
      cost: 5,
      dominance: 3,
      hp: 8,
      attack: 2,
      passiveSkill: {
        id: 'enemy-blackthorn-anchor-grasping-domain',
        description: 'Field에 있는 동안 이 카드의 지배력을 1 높인다.',
        type: 'PASSIVE',
        effects: [{ type: 'MODIFY_STAT', target: 'SELF', stat: 'DOMINANCE', amount: 1 }],
      },
    },
    rarity: 'EPIC',
    primaryRole: 'OCCUPATION',
    secondaryRole: 'DEFENSE',
    deckQuantity: 2,
    expectedSkillValue: 1.5,
    artDirection: {
      scene: 'a blasted woodland held by enormous black thorn roots',
      equipment: 'barbed anchor maul and dark layered plate',
      palette: 'black green, iron gray, and dark purple',
      pose: 'hauling the anchor maul downward as thorn roots spread from the impact',
    },
  }),
  defineCardDesign({
    faction: 'ENEMY',
    definition: {
      id: 'enemy-void-exiler',
      name: '공허 추방자',
      description: '공허의 틈으로 강한 적을 지우고 그 파괴에서 새 계책을 얻는 집행자다.',
      type: 'UNIT',
      cost: 6,
      dominance: 2,
      hp: 7,
      attack: 1,
      activeSkill: {
        id: 'enemy-void-exiler-cast-beyond',
        description: 'Active 사용 시 공격 범위 안의 대상에게 EXILED 상태를 추가한다.',
        type: 'ACTIVE',
        action: 'ATTACK',
        effects: [{ type: 'ADD_STATUS', target: 'ACTION_TARGET', statusId: 'EXILED' }],
      },
      reactiveSkill: {
        id: 'enemy-void-exiler-harvest-the-fall',
        description: '상대 카드가 파괴되면 카드 1장을 뽑는다.',
        type: 'REACTIVE',
        trigger: { type: 'CARD_DESTROYED', subject: 'OPPONENT' },
        effects: [{ type: 'DRAW', target: 'OWNER', count: 1 }],
      },
    },
    rarity: 'EPIC',
    primaryRole: 'DISRUPTION',
    secondaryRole: 'HAND',
    deckQuantity: 2,
    expectedSkillValue: 6.5,
    artDirection: {
      scene: 'a shattered moon gate opening into a starless void',
      equipment: 'void-edged greatsword and rune-bound executioner mantle',
      palette: 'black, ultraviolet, and icy cyan',
      pose: 'drawing the greatsword back as a narrow void rift opens along its edge',
    },
  }),
  defineCardDesign({
    faction: 'ENEMY',
    definition: {
      id: 'enemy-obsidian-champion',
      name: '흑요석 대전사',
      description: '무거운 흑요석 무기로 전열을 정면에서 분쇄하는 군단의 대전사다.',
      type: 'UNIT',
      cost: 7,
      dominance: 3,
      hp: 9,
      attack: 7,
    },
    rarity: 'RARE',
    primaryRole: 'ATTACK',
    secondaryRole: 'DEFENSE',
    deckQuantity: 1,
    expectedSkillValue: 0,
    artDirection: {
      scene: 'a broken blackstone causeway beneath storm clouds',
      equipment: 'massive obsidian halberd and reinforced dark plate',
      palette: 'obsidian black, storm gray, and crimson accents',
      pose: 'standing squarely with the halberd blade lowered toward the viewer',
    },
  }),
]);
