import { ASSET_KEYS } from '../../../game/assets/manifest';
import { CARD_FRAME_ASSET_KEYS, type CardFrameAssetKey } from '../../../game/assets/cardAssets';
import type { CardFrameVariant } from '../../../game/data/contracts';

export type PF2eSurfaceVariant =
  'panel' | 'control' | 'tab' | 'scrollTrack' | 'scrollThumb' | 'gridCell' | 'dialog' | 'button';
export const PF2E_VISUAL_STATES = [
  'idle',
  'hover',
  'pressed',
  'focused',
  'selected',
  'disabled',
] as const;
export type PF2eVisualState = (typeof PF2E_VISUAL_STATES)[number];

export const PF2E_LABEL_VARIANTS = [
  'heading',
  'section',
  'status',
  'tab',
  'primary',
  'danger',
] as const;
export type PF2eLabelVariant = (typeof PF2E_LABEL_VARIANTS)[number];

export const PF2E_BADGE_TYPES = [
  'default',
  'cost',
  'dominance',
  'attack',
  'health',
  'defense',
] as const;
export type PF2eBadgeType = (typeof PF2E_BADGE_TYPES)[number];

export interface PF2eSurfaceThemeStyle {
  readonly fillColor: number;
  readonly fillAlpha: number;
  readonly strokeColor: number;
  readonly strokeAlpha: number;
  readonly strokeWidth: number;
  readonly radius: number;
}

export interface PF2eVisualStateStyle {
  readonly fillAlphaScale: number;
  readonly strokeAlphaScale: number;
  readonly strokeColor: number | null;
}

export interface PF2eLabelThemeStyle {
  readonly backgroundVariant: PF2eSurfaceVariant;
  readonly fontFamily: string;
  readonly fontSize: number;
  readonly fontStyle: 'normal' | 'bold';
  readonly textColor: string;
  readonly strokeColor: string;
  readonly strokeThickness: number;
  readonly minHeight: number;
  readonly paddingX: number;
  readonly paddingY: number;
}

const PF2E_DEFAULT_FONT_FAMILY = 'Pretendard, system-ui, sans-serif';
const PF2E_MONO_FONT_FAMILY = 'D2Coding, ui-monospace, SFMono-Regular, Menlo, monospace';

export const PF2E_ELF_THEME = {
  colors: {
    backdrop: 0x06110d,
    surface: 0x0b2a1e,
    border: 0x9a7944,
    accent: 0x8cc9aa,
    modalCover: 0x020805,
    text: '#f2ead4',
    mutedText: '#a8bcae',
    accentText: '#bce8d0',
    dangerText: '#f0aaa0',
  },
  typography: {
    display: PF2E_DEFAULT_FONT_FAMILY,
    body: PF2E_DEFAULT_FONT_FAMILY,
    mono: PF2E_MONO_FONT_FAMILY,
  },
  spacing: {
    panelInset: 42,
    controlGap: 12,
    compactInset: 18,
    compactGap: 8,
  },
  radii: {
    control: 10,
  },
  strokes: {
    hairline: 1,
    control: 2,
  },
  sizes: {
    minimumTouchTarget: 48,
    treeRow: 54,
    treeToggle: 18,
    scrollbar: 24,
    badge: 64,
  },
  components: {
    phaseSeven: {
      screenTitleHeight: 72,
      screenStatusHeight: 54,
      screenSubtitleLineSpacing: 5,
      formWidth: 520,
      formLabelFontSize: 15,
      formFieldGap: 7,
      formSectionGap: 18,
      inputHeight: 54,
      inputPaddingX: 18,
      inputPaddingY: 13,
      inputFontSize: 17,
      inputCursorColor: '#bce8d0',
      inputSelectionColor: 0x315c49,
      listColumnsLandscape: 2,
      listColumnsPortrait: 1,
      actionPanelWidth: 340,
      summaryTitleFontSize: 18,
      summaryDetailFontSize: 14,
      statusLineSpacing: 5,
      choiceListHeight: 260,
      modalDepth: 1050,
      modalCoverAlpha: 0.82,
    },
    themeMod: {
      screenInset: 14,
      headerInsetY: 8,
      footerInsetY: 6,
      headerTextGap: 3,
      screenTitleFontSize: 28,
      instructionFontSize: 13,
      statusFontSize: 13,
      galleryHeadingHeight: 54,
      galleryHeadingFontSize: 15,
      galleryGap: 6,
    },
    tree: {
      inset: 28,
      topInset: 48,
      indent: 22,
      itemGap: 8,
      rowFontSize: 15,
      titleFontSize: 20,
      titlePaddingX: 18,
      titlePaddingY: 10,
      togglePadding: 12,
    },
    showcase: {
      inset: 32,
      sectionGap: 18,
      sampleGap: 12,
      minimumContentWidth: 220,
      titleFontSize: 30,
      bodyFontSize: 15,
      bodyLineSpacing: 7,
      sectionFontSize: 16,
      samplePaddingX: 20,
      samplePaddingY: 10,
      panelSampleHeight: 140,
      controlSampleHeight: 58,
      panelDemoHeight: 260,
      tabPagesDemoHeight: 380,
      scrollablePanelDemoHeight: 360,
      gridTableDemoHeight: 360,
      confirmDialogDemoHeight: 330,
      responsiveHeadingScale: 0.1,
      responsiveHeadingMinimum: 26,
    },
    tabPages: {
      inset: 0,
      tabGap: 0,
      pageGap: 0,
      pageInset: 38,
      tabWidth: 156,
      tabHeight: 70,
    },
    scrollablePanel: {
      maskPadding: 2,
      sliderGap: 12,
      wheelSpeed: 0.12,
      dragThreshold: 8,
      minThumbSize: 64,
    },
    gridTable: {
      columns: 2,
      cellHeight: 104,
      cellGap: 10,
      cellInsetX: 24,
      cellInsetY: 18,
      titleFontSize: 18,
      detailFontSize: 14,
    },
    cardGrid: {
      cellInset: 6,
      cellGap: 8,
      captionGap: 4,
      captionHeight: 22,
      captionFontSize: 13,
      dragThreshold: 14,
      dragPreviewWidth: 180,
      dragPreviewAlpha: 0.82,
      dragPreviewDepth: 1200,
    },
    confirmDialog: {
      inset: 42,
      titleFontSize: 28,
      contentFontSize: 17,
      buttonFontSize: 17,
      buttonPaddingX: 24,
      buttonPaddingY: 12,
      titleGap: 18,
      contentGap: 24,
      actionGap: 12,
      actionWidth: 176,
      coverAlpha: 0.78,
      depth: 1000,
    },
    badgeLabel: {
      badgePadding: 6,
      badgeFontSize: 18,
      variants: {
        default: {
          key: ASSET_KEYS.pf2eElfBadge,
          textColor: '#f2ead4',
          strokeColor: '#14241c',
        },
        cost: {
          key: ASSET_KEYS.pf2eElfBadgeCost,
          textColor: '#effbff',
          strokeColor: '#061b38',
        },
        dominance: {
          key: ASSET_KEYS.pf2eElfBadge,
          textColor: '#bce8d0',
          strokeColor: '#08251b',
        },
        attack: {
          key: ASSET_KEYS.pf2eElfBadgeAttack,
          textColor: '#f7e9bd',
          strokeColor: '#101820',
        },
        health: {
          key: ASSET_KEYS.pf2eElfBadgeHealth,
          textColor: '#fff5e8',
          strokeColor: '#4b080d',
        },
        defense: {
          key: ASSET_KEYS.pf2eElfBadgeDefense,
          textColor: '#f4ecd7',
          strokeColor: '#091727',
        },
      } satisfies Record<
        PF2eBadgeType,
        { readonly key: string; readonly textColor: string; readonly strokeColor: string }
      >,
    },
    buttons: {
      gap: 12,
      height: 58,
    },
    card: {
      compactWidth: 160,
      boardMinimumWidth: 72,
      boardMaximumWidth: 150,
      minimumWidth: 200,
      maximumWidth: 360,
      defaultWidth: 320,
      aspectRatio: 2 / 3,
      frameDisplayScale: 1.075,
      statBadgeSize: 56,
      statBadgeInset: 20,
      statBadgeFontSize: 18,
      contentInsetX: 38,
      contentBottomInset: 74,
      boardContentBottomInset: 38,
      contentHeight: 124,
      boardNameHeight: 58,
      contentPaddingX: 14,
      contentPaddingY: 11,
      contentGap: 5,
      contentBackgroundColor: 0x06110d,
      contentBackgroundAlpha: 0.86,
      nameFontSize: 21,
      rulesFontSize: 13,
      rulesLineSpacing: 3,
      nameTextColor: '#f7e9bd',
      rulesTextColor: '#f2ead4',
      textStrokeColor: '#06110d',
      selectedTint: 0xe6c768,
      legalTargetTint: 0x8cc9aa,
      disabledAlpha: 0.46,
      frameVariants: {
        COMMON: { key: CARD_FRAME_ASSET_KEYS.COMMON },
        RARE: { key: CARD_FRAME_ASSET_KEYS.RARE },
        EPIC: { key: CARD_FRAME_ASSET_KEYS.EPIC },
        LEGENDARY: { key: CARD_FRAME_ASSET_KEYS.LEGENDARY },
      } satisfies Record<CardFrameVariant, { readonly key: CardFrameAssetKey }>,
    },
    battlePresentation: {
      effectDepth: 900,
      approachFraction: 0.38,
      shakeDistance: 10,
      pulseScale: 1.08,
      entryScale: 0.84,
      deathScale: 0.85,
      impactStartScale: 0.35,
      impactEndScale: 1.5,
      impactRadius: 36,
      popupRise: 54,
      popupFontSize: 28,
      impactColor: 0xf2d38b,
      damageTextColor: '#ffb0a8',
      healTextColor: '#b9ffd1',
      statusTextColor: '#bce8d0',
      popupStrokeColor: '#06110d',
      popupStrokeThickness: 4,
    },
    battleBoard: {
      headerHeight: 44,
      headerFontSize: 16,
      slotGap: 6,
      rowGap: 8,
      zoneGap: 10,
      handInset: 8,
      handGap: 5,
    },
    battleDirect: {
      pileWidthRatio: 0.68,
      pileMinimumWidth: 52,
      pileGap: 3,
      pileInset: 5,
      pileLabelFontSize: 10,
      pileCountFontSize: 16,
      pileStackGap: 6,
      slotDominanceFontSize: 16,
      slotDominanceInsetY: 7,
      slotDominanceStrokeThickness: 3,
      commandInsetX: 10,
      commandGap: 8,
      commandStatusFontSize: 12,
      commandButtonFontSize: 12,
      commandButtonPaddingX: 6,
      commandStackBreakpoint: 700,
      commandCompactSummaryHeight: 30,
      handInset: 12,
      handHandleHeight: 38,
      handCardGap: 10,
      handTweenDuration: 180,
      handDepth: 800,
      previewDepth: 950,
      previewAlpha: 0.96,
      dragPreviewAlpha: 0.8,
      dragPreviewDepth: 1000,
      dragThreshold: 14,
    },
  },
  surfaces: {
    panel: {
      fillColor: 0x0b2a1e,
      fillAlpha: 0.94,
      strokeColor: 0x6f957b,
      strokeAlpha: 0.72,
      strokeWidth: 2,
      radius: 18,
    },
    control: {
      fillColor: 0x153a2c,
      fillAlpha: 0.96,
      strokeColor: 0x709981,
      strokeAlpha: 0.78,
      strokeWidth: 1,
      radius: 12,
    },
    tab: {
      fillColor: 0x123326,
      fillAlpha: 0.98,
      strokeColor: 0x8cc9aa,
      strokeAlpha: 0.66,
      strokeWidth: 1,
      radius: 12,
    },
    scrollTrack: {
      fillColor: 0x071811,
      fillAlpha: 0.82,
      strokeColor: 0x315c49,
      strokeAlpha: 0.58,
      strokeWidth: 1,
      radius: 12,
    },
    scrollThumb: {
      fillColor: 0x709981,
      fillAlpha: 0.94,
      strokeColor: 0xbce8d0,
      strokeAlpha: 0.78,
      strokeWidth: 1,
      radius: 12,
    },
    gridCell: {
      fillColor: 0x102f23,
      fillAlpha: 0.94,
      strokeColor: 0x557a65,
      strokeAlpha: 0.72,
      strokeWidth: 1,
      radius: 12,
    },
    dialog: {
      fillColor: 0x0b2319,
      fillAlpha: 0.99,
      strokeColor: 0xc8aa68,
      strokeAlpha: 0.92,
      strokeWidth: 2,
      radius: 22,
    },
    button: {
      fillColor: 0x1b4937,
      fillAlpha: 0.98,
      strokeColor: 0x9fc9ad,
      strokeAlpha: 0.86,
      strokeWidth: 2,
      radius: 12,
    },
  } satisfies Record<PF2eSurfaceVariant, PF2eSurfaceThemeStyle>,
  visualStates: {
    idle: { fillAlphaScale: 1, strokeAlphaScale: 1, strokeColor: null },
    hover: { fillAlphaScale: 1, strokeAlphaScale: 1, strokeColor: 0xbce8d0 },
    pressed: { fillAlphaScale: 0.78, strokeAlphaScale: 1, strokeColor: 0x8cc9aa },
    focused: { fillAlphaScale: 1, strokeAlphaScale: 1, strokeColor: 0xc8f3dc },
    selected: { fillAlphaScale: 1, strokeAlphaScale: 1, strokeColor: 0xe6c768 },
    disabled: { fillAlphaScale: 0.48, strokeAlphaScale: 0.46, strokeColor: null },
  } satisfies Record<PF2eVisualState, PF2eVisualStateStyle>,
  label: {
    heading: {
      backgroundVariant: 'control',
      fontFamily: PF2E_DEFAULT_FONT_FAMILY,
      fontSize: 44,
      fontStyle: 'bold',
      textColor: '#f7e9bd',
      strokeColor: '#26170d',
      strokeThickness: 2,
      minHeight: 86,
      paddingX: 42,
      paddingY: 18,
    },
    section: {
      backgroundVariant: 'control',
      fontFamily: PF2E_DEFAULT_FONT_FAMILY,
      fontSize: 26,
      fontStyle: 'bold',
      textColor: '#e9dfbd',
      strokeColor: '#26170d',
      strokeThickness: 1,
      minHeight: 62,
      paddingX: 34,
      paddingY: 14,
    },
    status: {
      backgroundVariant: 'control',
      fontFamily: PF2E_DEFAULT_FONT_FAMILY,
      fontSize: 17,
      fontStyle: 'bold',
      textColor: '#bce8d0',
      strokeColor: '#14241c',
      strokeThickness: 1,
      minHeight: 54,
      paddingX: 26,
      paddingY: 12,
    },
    tab: {
      backgroundVariant: 'tab',
      fontFamily: PF2E_DEFAULT_FONT_FAMILY,
      fontSize: 17,
      fontStyle: 'bold',
      textColor: '#d9f4e5',
      strokeColor: '#14241c',
      strokeThickness: 1,
      minHeight: 70,
      paddingX: 28,
      paddingY: 14,
    },
    primary: {
      backgroundVariant: 'button',
      fontFamily: PF2E_DEFAULT_FONT_FAMILY,
      fontSize: 17,
      fontStyle: 'bold',
      textColor: '#f7e9bd',
      strokeColor: '#26170d',
      strokeThickness: 1,
      minHeight: 58,
      paddingX: 28,
      paddingY: 14,
    },
    danger: {
      backgroundVariant: 'button',
      fontFamily: PF2E_DEFAULT_FONT_FAMILY,
      fontSize: 17,
      fontStyle: 'bold',
      textColor: '#f0aaa0',
      strokeColor: '#2a110f',
      strokeThickness: 1,
      minHeight: 58,
      paddingX: 28,
      paddingY: 14,
    },
  } satisfies Record<PF2eLabelVariant, PF2eLabelThemeStyle>,
} as const;
